#
# Copyright (c) 2023 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_BT_BUF_ACL_RX_SIZE=502
CONFIG_BT_BUF_ACL_TX_SIZE=502
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251

# Disable logs over UART
CONFIG_LOG=n
CONFIG_LOG_PRINTK=n
CONFIG_UART_CONSOLE=n

CONFIG_NRF_REGTOOL_VERBOSITY=1

# CONFIG_DEBUG_LED_ENABLED=y
CONFIG_GPIO=y

#CONFIG_IPC_SERVICE_ICMSG_BOND_NOTIFY_REPEAT_TO_MS=100
